<aside>
	<!--<div class="blog side-widget" data-blog-preset="tags">&nbsp;</div>-->
	<div class="blog side-widget" data-blog-preset="recent" data-blog-template-main="/cet/mce/capstone/_extra/templates/related-projects.html">&nbsp;</div>
	<div class="blog side-widget" data-blog-template-main="/cet/mce/capstone/_extra/templates/department-widget.html">&nbsp;</div>
	<div class="blog side-widget" data-blog-preset="archive">&nbsp;</div>
</aside>